{{- if .Values.agent }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "kubecost.agentStoreSecretName" . }}
data:
  object-store.yaml: {{ .Values.agentKey | b64enc }}
{{- end }}