{{- if .Values.kubecostMetrics }}
{{- if .Values.kubecostMetrics.metricsPod }}
{{- if .Values.kubecostMetrics.metricsPod.enabled }}
{{- if .Values.kubecostMetrics.metricsPod.serviceMonitor }}
{{- if .Values.kubecostMetrics.metricsPod.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubecost.kubeMetricsName" . }}
  labels:
    {{ include "kubecost.chartLabels" . | nindent 4 }}
    {{- if .Values.kubecostMetrics.metricsPod.serviceMonitor.additionalLabels }}
    {{ toYaml .Values.kubecostMetrics.metricsPod.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: tcp-metrics
      honorLabels: true
      interval: 1m
      scrapeTimeout: 10s
      path: /metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ include "kubecost.kubeMetricsName" . }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}