
apiVersion: v2
<<<<<<< HEAD
appVersion: "1.89.0-rc.0"
description: A Helm chart that sets up Kubecost, Prometheus, and Grafana to monitor
  cloud costs.
name: cost-analyzer
version: 1.89.0-rc.0
=======
appVersion: "1.88.1"
description: A Helm chart that sets up Kubecost, Prometheus, and Grafana to monitor
  cloud costs.
name: cost-analyzer
version: 1.88.1
>>>>>>> 6ea1df5f56c6559dd7b76ace22203fd77a91eadf
annotations:
  "artifacthub.io/links": |
    - name: Homepage
      url: https://www.kubecost.com
